version: '2'

services:
  mongodb:
    networks:
      - proxy-tier
  rscue.api:    
    environment:
      - VIRTUAL_HOST=api.rscue.center
      - LETSENCRYPT_HOST=api.rscue.center
      - LETSENCRYPT_EMAIL=ignacio@rscue.center
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy